# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
use_frameworks!
target 'HatenaMaze' do
pod 'SwiftyJSON'
pod 'Alamofire', '~> 3.0'
pod “SDWebImage”
end

target 'HatenaMazeTests' do

end

target 'HatenaMazeUITests' do

end

